name: tmsmobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# T
version: 1.0.1+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  get_storage: ^2.1.1
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_localizations:
  
    sdk: flutter
  rxdart: ^0.28.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  loading_indicator: ^3.1.1
  equatable: ^2.0.7
  socket_io_client: ^3.0.2
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  html: ^0.15.5  
  image_cropper: ^9.0.0
  connectivity_plus: ^6.1.4
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  calendar_date_picker2: ^2.0.0
  flutter_widget_from_html: ^0.16.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  
  fonts:
    - family: app_font
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: crimson
      fonts:
        - asset: fonts/CrimsonPro-Regular.ttf
    - family: mm_font
      fonts:
        - asset: fonts/Padauk-Regular.ttf
  
