import 'package:flutter/material.dart';

const Color kBackgroundColor = Color(0xFFFFFFFF);
const Color kPrimaryColor = Color(0xFF03045E);
const Color kThirdColor = Color(0xFF00B4D8);
const Color kSecondaryColor = Color(0xFF48CAE4);
const Color kWhiteColor = Colors.white;
const Color kInputBackgroundColor = Color(0xFFEEEEEE);
const Color kGreyColor = Color.fromARGB(255, 216, 216, 216);
const Color kSecondGreyColor = Color(0xEEEEEECC);
const Color kYellowColor = Color(0xFFFFA500);
const Color kBlackColor = Color(0xFF444445);
const Color kGreenColor = Color(0xFF28C76F);
const Color kOrangeColor = Color(0xFFF86111);
const Color kPurpleColor = Color(0xFF9747FF);
const Color kBlueColor = Color(0xFF0057FF);
const Color kRedColor = Color(0xFFFF0000);
const Color kNewBlueColor = Color(0xFF012D67);
const Color kDarkBlueColor = Color(0xFF012D67);
const Color kThirdGrayColor = Color(0xffDFDFDF);
const Color kSkyBlueColor = Color.fromRGBO(217, 223, 232, 1);
const Color kSecondWhiteColor = Color(0xFFF1F1F1);